"""empty message

Revision ID: 9024525752fd
Revises: 
Create Date: 2020-03-22 10:28:39.230282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9024525752fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=100), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apellido'),
    sa.UniqueConstraint('direccion'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('Factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tienda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rut', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=100), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave'),
    sa.UniqueConstraint('direccion'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('CategoriaTienda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tienda_id'], ['Tienda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('DetalleFactura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['Factura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('foto', sa.String(length=100), nullable=False),
    sa.Column('stock', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.String(length=100), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tienda_id'], ['Tienda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave'),
    sa.UniqueConstraint('foto'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('precio'),
    sa.UniqueConstraint('stock')
    )
    op.create_table('CategoriaProductos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['Productos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CategoriaProductos')
    op.drop_table('Productos')
    op.drop_table('DetalleFactura')
    op.drop_table('CategoriaTienda')
    op.drop_table('Tienda')
    op.drop_table('Factura')
    op.drop_table('Usuario')
    # ### end Alembic commands ###
